version: '3.9'

services:
  infra:
    build:
      context: ./
      dockerfile: Dockerfile
      ssh:
        - default
    image: diogoandrade/nlwspace:test
    secrets:
      - github-ssh-key
    container_name: nlwspace
    ports:
      - '8000:1234'
      - '5555:5555'
    expose:
      - 8000
      - 5555
    volumes:
      - ${PWD}:/app
    tty: true
    entrypoint: ['/bin/bash']
secrets:
  github-ssh-key:
    file: ${HOME}/.ssh/id_ed25519
